const { ROLES, PERMISSIONS } = require('./constants');

// Role-Permission Mapping
const rolePermissions = {
  // ADMIN - Full system access
  [ROLES.ADMIN]: [
    // User Management
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,

    // Lead Management
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.READ_LEAD,
    PERMISSIONS.READ_ALL_LEADS,
    PERMISSIONS.UPDATE_LEAD,
    PERMISSIONS.DELETE_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.CONVERT_LEAD,

    // Account Management
    PERMISSIONS.CREATE_ACCOUNT,
    PERMISSIONS.READ_ACCOUNT,
    PERMISSIONS.READ_ALL_ACCOUNTS,
    PERMISSIONS.UPDATE_ACCOUNT,
    PERMISSIONS.DELETE_ACCOUNT,

    // Contact Management
    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.READ_CONTACT,
    PERMISSIONS.READ_ALL_CONTACTS,
    PERMISSIONS.UPDATE_CONTACT,
    PERMISSIONS.DELETE_CONTACT,

    // Deal Management
    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.READ_DEAL,
    PERMISSIONS.READ_ALL_DEALS,
    PERMISSIONS.UPDATE_DEAL,
    PERMISSIONS.DELETE_DEAL,

    // Appointment Management
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.COMPLETE_APPOINTMENT,

    // MOM Management
    PERMISSIONS.CREATE_MOM,
    PERMISSIONS.READ_MOM,
    PERMISSIONS.UPDATE_MOM,
    PERMISSIONS.DELETE_MOM,
    PERMISSIONS.SHARE_MOM,

    // Activity Management
    PERMISSIONS.CREATE_ACTIVITY,
    PERMISSIONS.READ_ACTIVITY,
    PERMISSIONS.UPDATE_ACTIVITY,
    PERMISSIONS.DELETE_ACTIVITY,

    // Proposal Management
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    PERMISSIONS.DELETE_PROPOSAL,
    PERMISSIONS.APPROVE_PROPOSAL,
    PERMISSIONS.REJECT_PROPOSAL,

    // Sales Order Management
    PERMISSIONS.CREATE_SALES_ORDER,
    PERMISSIONS.READ_SALES_ORDER,
    PERMISSIONS.UPDATE_SALES_ORDER,
    PERMISSIONS.DELETE_SALES_ORDER,

    // Reports & Dashboard
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ALL_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD,

    // Settings
    PERMISSIONS.UPDATE_SETTINGS
  ],

  // SALES_MANAGER - Team management & approvals
  [ROLES.SALES_MANAGER]: [
    // User Management - Read only
    PERMISSIONS.READ_USER,

    // Lead Management
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.READ_LEAD,
    PERMISSIONS.READ_ALL_LEADS,
    PERMISSIONS.UPDATE_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.CONVERT_LEAD,

    // Account Management
    PERMISSIONS.CREATE_ACCOUNT,
    PERMISSIONS.READ_ACCOUNT,
    PERMISSIONS.READ_ALL_ACCOUNTS,
    PERMISSIONS.UPDATE_ACCOUNT,

    // Contact Management
    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.READ_CONTACT,
    PERMISSIONS.READ_ALL_CONTACTS,
    PERMISSIONS.UPDATE_CONTACT,

    // Deal Management
    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.READ_DEAL,
    PERMISSIONS.READ_ALL_DEALS,
    PERMISSIONS.UPDATE_DEAL,

    // Appointment Management
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.COMPLETE_APPOINTMENT,

    // MOM Management
    PERMISSIONS.CREATE_MOM,
    PERMISSIONS.READ_MOM,
    PERMISSIONS.UPDATE_MOM,
    PERMISSIONS.DELETE_MOM,
    PERMISSIONS.SHARE_MOM,

    // Activity Management
    PERMISSIONS.CREATE_ACTIVITY,
    PERMISSIONS.READ_ACTIVITY,
    PERMISSIONS.UPDATE_ACTIVITY,
    PERMISSIONS.DELETE_ACTIVITY,

    // Proposal Management
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    PERMISSIONS.APPROVE_PROPOSAL,
    PERMISSIONS.REJECT_PROPOSAL,

    // Sales Order Management
    PERMISSIONS.CREATE_SALES_ORDER,
    PERMISSIONS.READ_SALES_ORDER,
    PERMISSIONS.UPDATE_SALES_ORDER,

    // Reports & Dashboard
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ALL_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ],

  // SALES_PERSON - Own records only
  [ROLES.SALES_PERSON]: [
    // User Management - Read only (self)
    PERMISSIONS.READ_USER,

    // Lead Management
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.READ_LEAD,
    PERMISSIONS.UPDATE_LEAD,
    PERMISSIONS.CONVERT_LEAD,

    // Account Management
    PERMISSIONS.CREATE_ACCOUNT,
    PERMISSIONS.READ_ACCOUNT,
    PERMISSIONS.UPDATE_ACCOUNT,

    // Contact Management
    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.READ_CONTACT,
    PERMISSIONS.UPDATE_CONTACT,

    // Deal Management
    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.READ_DEAL,
    PERMISSIONS.UPDATE_DEAL,

    // Appointment Management
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.COMPLETE_APPOINTMENT,

    // MOM Management
    PERMISSIONS.CREATE_MOM,
    PERMISSIONS.READ_MOM,
    PERMISSIONS.UPDATE_MOM,
    PERMISSIONS.DELETE_MOM,
    PERMISSIONS.SHARE_MOM,

    // Activity Management
    PERMISSIONS.CREATE_ACTIVITY,
    PERMISSIONS.READ_ACTIVITY,
    PERMISSIONS.UPDATE_ACTIVITY,
    PERMISSIONS.DELETE_ACTIVITY,

    // Proposal Management
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,

    // Sales Order Management
    PERMISSIONS.CREATE_SALES_ORDER,
    PERMISSIONS.READ_SALES_ORDER,

    // Reports & Dashboard
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ]
};

// Check if role has permission
const hasPermission = (roleId, permission) => {
  const permissions = rolePermissions[roleId] || [];
  return permissions.includes(permission);
};

// Get all permissions for a role
const getRolePermissions = (roleId) => {
  return rolePermissions[roleId] || [];
};

module.exports = {
  rolePermissions,
  hasPermission,
  getRolePermissions
};