const { ROLES, PERMISSIONS } = require('./constants');

// Role-Permission Mapping
const rolePermissions = {
  // ADMIN - Full system access
  [ROLES.ADMIN]: [
    // User Management
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    
    // Lead Management - All permissions
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.READ_LEAD,
    PERMISSIONS.READ_ALL_LEADS,
    PERMISSIONS.UPDATE_LEAD,
    PERMISSIONS.DELETE_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.QUALIFY_LEAD,
    
    // Appointment Management - All permissions
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.COMPLETE_APPOINTMENT,
    
    // MOM Management - All permissions
    PERMISSIONS.CREATE_MOM,
    PERMISSIONS.READ_MOM,
    PERMISSIONS.UPDATE_MOM,
    PERMISSIONS.DELETE_MOM,
    PERMISSIONS.SHARE_MOM,
    
    // Activity Management - All permissions
    PERMISSIONS.CREATE_ACTIVITY,
    PERMISSIONS.READ_ACTIVITY,
    PERMISSIONS.UPDATE_ACTIVITY,
    PERMISSIONS.DELETE_ACTIVITY,
    
    // Opportunity Management - All
    PERMISSIONS.CREATE_OPPORTUNITY,
    PERMISSIONS.READ_OPPORTUNITY,
    PERMISSIONS.READ_ALL_OPPORTUNITIES,
    PERMISSIONS.UPDATE_OPPORTUNITY,
    PERMISSIONS.DELETE_OPPORTUNITY,
    
    // Proposal Management - All
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    PERMISSIONS.DELETE_PROPOSAL,
    PERMISSIONS.APPROVE_PROPOSAL,
    PERMISSIONS.REJECT_PROPOSAL,
    
    // Sales Order Management - All
    PERMISSIONS.CREATE_SALES_ORDER,
    PERMISSIONS.READ_SALES_ORDER,
    PERMISSIONS.UPDATE_SALES_ORDER,
    PERMISSIONS.DELETE_SALES_ORDER,
    
    // Reports & Dashboard
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ALL_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  // SALES_MANAGER - Team management & approvals
  [ROLES.SALES_MANAGER]: [
    // User Management - Read only
    PERMISSIONS.READ_USER,
    
    // Lead Management - Can view all and assign
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.READ_LEAD,
    PERMISSIONS.READ_ALL_LEADS,
    PERMISSIONS.UPDATE_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.QUALIFY_LEAD,
    
    // Appointment Management - Full access
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.COMPLETE_APPOINTMENT,
    
    // MOM Management - Full access
    PERMISSIONS.CREATE_MOM,
    PERMISSIONS.READ_MOM,
    PERMISSIONS.UPDATE_MOM,
    PERMISSIONS.DELETE_MOM,
    PERMISSIONS.SHARE_MOM,
    
    // Activity Management - Full access
    PERMISSIONS.CREATE_ACTIVITY,
    PERMISSIONS.READ_ACTIVITY,
    PERMISSIONS.UPDATE_ACTIVITY,
    PERMISSIONS.DELETE_ACTIVITY,
    
    // Opportunity Management - Can view all
    PERMISSIONS.CREATE_OPPORTUNITY,
    PERMISSIONS.READ_OPPORTUNITY,
    PERMISSIONS.READ_ALL_OPPORTUNITIES,
    PERMISSIONS.UPDATE_OPPORTUNITY,
    
    // Proposal Management - Can approve/reject
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    PERMISSIONS.APPROVE_PROPOSAL,
    PERMISSIONS.REJECT_PROPOSAL,
    
    // Sales Order Management
    PERMISSIONS.CREATE_SALES_ORDER,
    PERMISSIONS.READ_SALES_ORDER,
    PERMISSIONS.UPDATE_SALES_ORDER,
    
    // Reports & Dashboard
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ALL_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  // SALES_PERSON - Own leads only
  [ROLES.SALES_PERSON]: [
    // User Management - Read only (self)
    PERMISSIONS.READ_USER,
    
    // Lead Management - Own leads only
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.READ_LEAD,
    PERMISSIONS.UPDATE_LEAD,
    PERMISSIONS.QUALIFY_LEAD,
    
    // Appointment Management - Own leads only
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.COMPLETE_APPOINTMENT,
    
    // MOM Management - Own leads only
    PERMISSIONS.CREATE_MOM,
    PERMISSIONS.READ_MOM,
    PERMISSIONS.UPDATE_MOM,
    PERMISSIONS.DELETE_MOM,
    PERMISSIONS.SHARE_MOM,
    
    // Activity Management - Own leads only
    PERMISSIONS.CREATE_ACTIVITY,
    PERMISSIONS.READ_ACTIVITY,
    PERMISSIONS.UPDATE_ACTIVITY,
    PERMISSIONS.DELETE_ACTIVITY,
    
    // Opportunity Management - Own only
    PERMISSIONS.CREATE_OPPORTUNITY,
    PERMISSIONS.READ_OPPORTUNITY,
    PERMISSIONS.UPDATE_OPPORTUNITY,
    
    // Proposal Management - Can create and submit
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    
    // Sales Order Management
    PERMISSIONS.CREATE_SALES_ORDER,
    PERMISSIONS.READ_SALES_ORDER,
    
    // Reports & Dashboard - Own only
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ]
};

// Check if role has permission
const hasPermission = (roleId, permission) => {
  const permissions = rolePermissions[roleId] || [];
  return permissions.includes(permission);
};

// Get all permissions for a role
const getRolePermissions = (roleId) => {
  return rolePermissions[roleId] || [];
};

module.exports = {
  rolePermissions,
  hasPermission,
  getRolePermissions
};